version: '3.8'
services:
  twitter-server:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    container_name: tra-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata: