version: "3.8"

services:
    twitter-server:
        build: .
        container_name: twitter-server
        restart: always
        volumes:
            - .:/app
        ports:
            - 4000:4000
        env_file:
            - .env
